title: Mestara
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
layout_type: full-width
style: classic
palette: brown
mode: light
base_font: serif
header:
  logo: images/Logo Mestara.png
  has_primary_nav: true
  primary_nav_links:
    - label: Mentorship
      url: /mentorship
      style: link
    - label: Empowerment
      url: /berdaya
      style: link
    - label: English Convo Club
      url: '#convo-club'
      style: link
      has_icon: false
      icon: arrow-left
      icon_position: right
      new_window: false
      no_follow: false
    - label: Webinar
      url: '#'
      style: link
      has_icon: false
      icon: arrow-left
      icon_position: right
      new_window: false
      no_follow: false
  has_secondary_nav: true
  secondary_nav_links:
    - label: Contact us
      style: link
      url: /general-enquiries
    - label: Donate
      style: secondary
      url: /donate
  has_anncmnt: false
  anncmnt_align: left
  anncmnt_is_home_only: false
  anncmnt_has_close: false
  anncmnt_id: new-features
  logo_alt: Mestara
footer:
  has_primary_nav: false
  primary_nav_title: Company
  primary_nav_links:
    - label: About
      url: /about
      style: link
    - label: Style Guide
      url: /style-guide
      style: link
  has_secondary_nav: false
  secondary_nav_title: Blog
  secondary_nav_links:
    - label: News
      url: /blog/category/news
      style: link
    - label: General
      url: /blog/category/general
      style: link
    - label: Tutorials
      url: /blog/category/tutorials
      style: link
  has_tertiary_nav: false
  tertiary_nav_title: Legal
  tertiary_nav_links:
    - label: Terms & Conditions
      url: /terms-conditions
      style: link
    - label: Privacy Policy
      url: /privacy-policy
      style: link
  has_social: true
  social_links:
    - label: LinkedIn
      url: 'https://www.linkedin.com/company/mestara/'
      style: link
      has_icon: true
      icon: linkedin
      icon_position: center
      new_window: true
    - label: Instagram
      url: 'https://www.instagram.com/mestaracom/'
      style: link
      has_icon: true
      icon: instagram
      icon_position: center
      new_window: true
      no_follow: false
      type: action
  content: >-
    &copy; Stackbit. All rights reserved. This Jamstack site was created with <a
    href="https://www.stackbit.com/?utm_source=deployed-footer" target="_blank"
    rel="noopener">Stackbit</a>.
sass:
  indentWidth: 4
  style: expanded
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
domain: 'http://www.mestara.com'
favicon: images/magenta-aluminum.png
